"""Updated the foreign key constraints

Revision ID: 03e7d66b1ff1
Revises: 0002_create_tables
Create Date: 2026-02-10 13:06:03.218834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03e7d66b1ff1'
down_revision: Union[str, Sequence[str], None] = '0002_create_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('session_id', sa.Integer(), nullable=False))
    op.alter_column('flashcards', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('flashcards', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('flashcards', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'notes', ['session_id'], ['id'])
    op.drop_column('flashcards', 'note_id')
    op.alter_column('notes', 'raw_ocr_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notes', 'clean_ocr_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.alter_column('processing_jobs', 'job_type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ocr', 'summary', 'flashcards', 'quiz', name='processing_job_type'),
               existing_nullable=False)
    op.alter_column('processing_jobs', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('pending', 'running', 'done', 'failed', name='processing_job_status'),
               existing_nullable=False)
    op.alter_column('processing_jobs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('quizzes', sa.Column('session_id', sa.Integer(), nullable=False))
    op.alter_column('quizzes', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quizzes', 'options',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quizzes', 'correct_answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quizzes', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'notes', ['session_id'], ['id'])
    op.drop_column('quizzes', 'note_id')
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('pending', 'running', 'done', 'failed', name='session_status'),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.add_column('summaries', sa.Column('session_id', sa.Integer(), nullable=False))
    op.alter_column('summaries', 'summary_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('summaries', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'notes', ['session_id'], ['id'])
    op.drop_column('summaries', 'note_id')
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.add_column('summaries', sa.Column('note_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'summaries', type_='foreignkey')
    op.create_foreign_key(None, 'summaries', 'notes', ['note_id'], ['id'])
    op.alter_column('summaries', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('summaries', 'summary_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('summaries', 'session_id')
    op.alter_column('sessions', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('sessions', 'status',
               existing_type=sa.Enum('pending', 'running', 'done', 'failed', name='session_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.add_column('quizzes', sa.Column('note_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'quizzes', type_='foreignkey')
    op.create_foreign_key(None, 'quizzes', 'notes', ['note_id'], ['id'])
    op.alter_column('quizzes', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('quizzes', 'correct_answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('quizzes', 'options',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('quizzes', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('quizzes', 'session_id')
    op.alter_column('processing_jobs', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('processing_jobs', 'status',
               existing_type=sa.Enum('pending', 'running', 'done', 'failed', name='processing_job_status'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('processing_jobs', 'job_type',
               existing_type=sa.Enum('ocr', 'summary', 'flashcards', 'quiz', name='processing_job_type'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('notes', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('notes', 'clean_ocr_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notes', 'raw_ocr_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('flashcards', sa.Column('note_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.create_foreign_key(None, 'flashcards', 'notes', ['note_id'], ['id'])
    op.alter_column('flashcards', 'created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               nullable=True)
    op.alter_column('flashcards', 'answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('flashcards', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('flashcards', 'session_id')
    # ### end Alembic commands ###
