"""Removed the processing job model

Revision ID: 081bb3895706
Revises: faa13a08ee58
Create Date: 2026-02-16 22:22:21.823469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '081bb3895706'
down_revision: Union[str, Sequence[str], None] = 'faa13a08ee58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_type', postgresql.ENUM('OCR', 'SUMMARY', 'FLASHCARD', 'QUIZ', name='processing_job_type'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'FINISHED', 'FAILED', name='processing_job_status'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('processing_jobs_note_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('processing_jobs_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('processing_jobs_pkey'))
    )
    # ### end Alembic commands ###
