"""Made changes to the foreign keys

Revision ID: 4c7890e077f8
Revises: 0002_create_tables
Create Date: 2026-02-11 22:33:33.525172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c7890e077f8'
down_revision: Union[str, Sequence[str], None] = '0002_create_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_notes',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name='fk_notes_table'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='fk_sessions_table'),
    sa.PrimaryKeyConstraint('session_id', 'note_id')
    )
    op.add_column('flashcards', sa.Column('session_id', sa.Integer(), nullable=False))
    op.alter_column('flashcards', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('flashcards', 'answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('flashcards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('flashcards_note_id_fkey'), 'flashcards', type_='foreignkey')
    op.create_foreign_key('fk_flashcards_session', 'flashcards', 'sessions', ['session_id'], ['id'])
    op.drop_column('flashcards', 'note_id')
    op.alter_column('notes', 'raw_ocr_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('notes', 'clean_ocr_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('notes_session_id_fkey'), 'notes', type_='foreignkey')
    op.drop_column('notes', 'session_id')
    op.alter_column('processing_jobs', 'error_message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('quizzes', sa.Column('session_id', sa.Integer(), nullable=False))
    op.alter_column('quizzes', 'question',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quizzes', 'options',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quizzes', 'correct_answer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('quizzes_note_id_fkey'), 'quizzes', type_='foreignkey')
    op.create_foreign_key('fk_quizzes_session', 'quizzes', 'sessions', ['session_id'], ['id'])
    op.drop_column('quizzes', 'note_id')
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_column('sessions', 'note_count')
    op.add_column('summaries', sa.Column('session_id', sa.Integer(), nullable=False))
    op.alter_column('summaries', 'summary_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('summaries_note_id_fkey'), 'summaries', type_='foreignkey')
    op.create_foreign_key('fk_summaries_session', 'summaries', 'sessions', ['session_id'], ['id'])
    op.drop_column('summaries', 'note_id')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.add_column('summaries', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_summaries_session', 'summaries', type_='foreignkey')
    op.create_foreign_key(op.f('summaries_note_id_fkey'), 'summaries', 'notes', ['note_id'], ['id'])
    op.alter_column('summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('summaries', 'summary_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('summaries', 'session_id')
    op.add_column('sessions', sa.Column('note_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.add_column('quizzes', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_quizzes_session', 'quizzes', type_='foreignkey')
    op.create_foreign_key(op.f('quizzes_note_id_fkey'), 'quizzes', 'notes', ['note_id'], ['id'])
    op.alter_column('quizzes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('quizzes', 'correct_answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('quizzes', 'options',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('quizzes', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('quizzes', 'session_id')
    op.alter_column('processing_jobs', 'error_message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('notes', sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notes_session_id_fkey'), 'notes', 'sessions', ['session_id'], ['id'])
    op.alter_column('notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('notes', 'clean_ocr_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('notes', 'raw_ocr_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.add_column('flashcards', sa.Column('note_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_flashcards_session', 'flashcards', type_='foreignkey')
    op.create_foreign_key(op.f('flashcards_note_id_fkey'), 'flashcards', 'notes', ['note_id'], ['id'])
    op.alter_column('flashcards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               nullable=True)
    op.alter_column('flashcards', 'answer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('flashcards', 'question',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('flashcards', 'session_id')
    op.drop_table('sessions_notes')
    # ### end Alembic commands ###
