"""Removed the enum from the Session model

Revision ID: 5d4f17ce7433
Revises: 72876ba565f5
Create Date: 2026-02-22 22:12:10.070926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4f17ce7433'
down_revision: Union[str, Sequence[str], None] = '72876ba565f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'status',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###
