"""Edited the enum

Revision ID: 72876ba565f5
Revises: b8b84c5b02e3
Create Date: 2026-02-22 19:41:20.855601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72876ba565f5'
down_revision: Union[str, Sequence[str], None] = 'b8b84c5b02e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'status',
               existing_type=postgresql.ENUM('PENDING', 'RUNNING', 'FINISHED', 'FAILED', name='session_status'),
               type_=sa.Enum('pending', 'running', 'finished', 'failed', name='session_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'status',
               existing_type=sa.Enum('pending', 'running', 'finished', 'failed', name='session_status', native_enum=False),
               type_=postgresql.ENUM('PENDING', 'RUNNING', 'FINISHED', 'FAILED', name='session_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
