"""Added the fields for the streak for the user

Revision ID: b8b84c5b02e3
Revises: 081bb3895706
Create Date: 2026-02-21 16:30:52.893102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b84c5b02e3'
down_revision: Union[str, Sequence[str], None] = '081bb3895706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('current_streak', sa.Integer(), nullable=True)
    )
    op.execute(
        sa.text("UPDATE users SET current_streak = 0")
    )
    op.alter_column(
        'users',
        'current_streak',
        nullable=False
    )
    op.add_column(
        'users',
        sa.Column('last_active_date', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###
