"""Added the question model

Revision ID: faa13a08ee58
Revises: 4c7890e077f8
Create Date: 2026-02-12 10:06:12.433859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa13a08ee58'
down_revision: Union[str, Sequence[str], None] = '4c7890e077f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='fk_questions_quiz'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('quizzes', 'question')
    op.drop_column('quizzes', 'options')
    op.drop_column('quizzes', 'correct_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quizzes', sa.Column('options', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('quizzes', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('questions')
    # ### end Alembic commands ###
